
camunda:
  bpm:
    admin-user:
      id: admin
      password: admin
      firstName: Administrator
    filter:
      create: All tasks
    database:
      schema-update: create-drop

spring:
  datasource:
    url: jdbc:h2:file:~/projects/cardif/camunda-spring-boot/camunda-db;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE
    username: admin
    password:
    initialization-mode: always

